### ISSUE TITLE
Feature request: Jack Transport tempo sync

### ISSUE THREAD

**Issue by milkmiruku** [diovudau/Patroneo#1]
Being able to sync bpm across a session allows for an extra level of expression for both studio and live performance. Could this be made possible in Patroneo?

**Comment by diovudau** [comment]
That is implemented but has a bug, one of the few that prevent an official release yet (See README)
You can send out jack transport tempo but not receive them at the moment.

There is only one tempo in the session though and this will stay that way. The tempo is already a compromise for convenience. The optimal solution would be handling tempo changes and ramps in a dedicated external program altogether.

**Comment by diovudau** [comment]
Implement and working. Also needs rebuild of calfbox from just now.
