### ISSUE TITLE
Jump to start button whilst playing can cause missing note offs

### ISSUE THREAD

**Issue by milkmiruku** [diovudau/Patroneo#2]
Which can result in a continuous note from the synth requiring the use of the host panic button.

Edit; missed note offs also caused through jumping around the track by clicking with the measure bar at the top.

**Comment by diovudau** [comment]
True. Will be fixed.

**Comment by diovudau** [comment]
Should be fixed, please test and confirm.

**Comment by milkmiruku** [comment]
That's fixed, though removing a note before it has finished playing also causes a hang.

**Comment by diovudau** [comment]
Good.
Deleting midi notes while playing is absolutely non-trivial to fix. That has to get postponed for now.
